version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    command: node index.js
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017/mydatabase
